[project]
name = "Qualiscore"
version = "0.1.0"
description = ""
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.14"
authors = [
  { name = "Quentin LIENHARDT", email = "quentin.lienhardt@actimage.com" },
]
dependencies = [
  # Runner
  "pyyaml>=6.0.3",
  # Registry
  "niquests>=3.21.0",
  # DOM
  "camoufox>=0.5.5",
  "beautifulsoup4>=4.15.0",
  # Lighthouse
  "playwright==1.60.0",
  # Ecoindex
  "ecoindex-scraper>=3.17.0",
]

[dependency-groups]
dev-dependencies = ["ruff>=0.16.4"]

[tool.uv.sources]
ecoindex-scraper = { git = "https://github.com/Quentium-Forks/EcoIndex_python.git", subdirectory = "projects/ecoindex_scraper", rev = "feat/camoufox" }

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
  # flake8-bugbear
  "B",
  # flake8-comprehensions
  "C4",
  # pycodestyle errors
  "E",
  # pyflakes
  "F",
  # flake8-logging-format
  "G",
  # isort
  "I",
  # flake8-implicit-str-concat
  "ISC",
  # pylint convention
  "PLC",
  # pylint errors
  "PLE",
  # flake8-simplify
  "SIM",
  # pyupgrade
  "UP",
  # pycodestyle warnings
  "W",
]
ignore = [
  # Do not perform function call `Depends` in argument defaults
  "B008",
  # Line too long
  "E501",
  # Unnecessary dict comprehension
  "C420",
]
